### ISSUE TITLE
[ALPHA] Problem parsing "ALPHA" in version string

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#50]
Game crashes trying to parse a version string containing "ALPHA":

java.lang.NumberFormatException: For input string: "1ALPHA"

```
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at org.blockartistry.mod.ThermalRecycling.VersionCheck$SoftwareVersion.<init>(VersionCheck.java:101)
at org.blockartistry.mod.ThermalRecycling.VersionCheck.<clinit>(VersionCheck.java:55)
```

**Comment by OreCruncher** [comment]
Released in v0.4.1.1ALPHA
