### ISSUE TITLE
[ALPHA] Error registering Forestry crates

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#51]
Crash when attempting to register Forestry crates:

[12:31:33] [Client thread/WARN] [FML/recycling]: \* Illegal extra prefix recycling for name recycling:cratedSuperiorScrapBox, invalid registry invocation/invalid name?
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:805)
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at forestry.core.proxy.ProxyCommon.registerItem(ProxyCommon.java:81)
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at forestry.storage.CrateRegistry.registerCrate(CrateRegistry.java:38)
[12:31:33] [Client thread/WARN] [FML/recycling]: \*  at forestry.storage.CrateRegistry.registerCrate(CrateRegistry.java:64)...
[12:31:33] [Client thread/WARN] [FML/recycling]: ****************************************

**Comment by OreCruncher** [comment]
Released in v0.4.1.1ALPHA
