### ISSUE TITLE
[1.1.0.4] Inventory tooltip crashing on BCA canister

### ISSUE THREAD

**Issue by mrogaski** [OreCruncher/ThermalRecycling#95]
After upgrading to 1.1.0.4, we're seeing this when a player opens their inventory while it has a BCA canister.

```
Description: Updating screen events

java.lang.RuntimeException: Missing profile for Item buildcraftAdditions.items.ItemBucketBCA@328a4bda
    at org.blockartistry.mod.ThermalRecycling.data.registry.ItemRegistry.getProfile(ItemRegistry.java:65)
    at org.blockartistry.mod.ThermalRecycling.data.registry.ItemRegistry.get(ItemRegistry.java:71)
    at org.blockartistry.mod.ThermalRecycling.tooltip.ScrapToolTip.addToToolTip(ScrapToolTip.java:40)
    at org.blockartistry.mod.ThermalRecycling.tooltip.CachingToolTip.accept(CachingToolTip.java:54)
    at org.blockartistry.mod.ThermalRecycling.events.ToolTipEventHandler.onToolTipEvent(ToolTipEventHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1017_ToolTipEventHandler_onToolTipEvent_ItemTooltipEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash report at https://github.com/AIE-Guild/AIE-Nomads-Modpack/issues/101

**Comment by OreCruncher** [comment]
I cannot duplicate in my sandbox using BC 7.1.14 and BCA 2.2.5.  I am using Forge 1614 though I cannot imagine Forge being the issue here.  What this error is saying that there is an item in the game that for some reason was not present when Thermal Recycling scanned the the internal item list in Minecraft/Forge.  This occuring in the release version of your pack on Curse?

**Comment by OreCruncher** [comment]
OK - managed to make it crash with the modpack.  What is interesting is the item is "bcadditions:fuelgasBucket".  It does not show in NEI.  I get it to crash by going into creative mode and clicking the Minecraft search button.  I will keep digging.

**Comment by mrogaski** [comment]
Yep. we saw it under creative mode.  Let me know if you need any other info.

Thanks!

**Comment by OreCruncher** [comment]
I don't know much about BCA - is the fuel gas bucket a thing or is it something that is only available via creative?  Reason I ask is that it isn't registered in the item list when Thermal Recycling scans the registered items (thus why there isn't a "profile").

**Comment by OreCruncher** [comment]
Posted fix to CurseForge.  Should be showing up as soon as they approve it. http://minecraft.curseforge.com/projects/thermal-recycling/files

**Comment by mrogaski** [comment]
I just tested it and the update successfully prevented the crash.

**Comment by OreCruncher** [comment]
Cool!
